# Generated by Django 5.2.4 on 2025-08-03 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name="Ім'я")),
                ('last_name', models.CharField(max_length=100, verbose_name='Прізвище')),
                ('patronymic', models.CharField(blank=True, max_length=100, verbose_name='По-батькові')),
                ('level', models.CharField(choices=[('JUN', 'Junior'), ('MID', 'Middle'), ('SEN', 'Senior'), ('LEAD', 'Team Lead')], max_length=4, verbose_name='Рівень')),
            ],
            options={
                'verbose_name': 'Співробітник',
                'verbose_name_plural': 'Співробітники',
            },
        ),
        migrations.CreateModel(
            name='SalaryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField(verbose_name='Місяць (1-12)')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Рік (напр. 2025)')),
                ('actual_hours', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Фактично відпрацьовані години')),
                ('standard_hours', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Норма годин на місяць')),
                ('tasks_completed_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Загальна вартість завдань (грн)')),
                ('usd_rate', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Курс USD на цей місяць')),
                ('eur_rate', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Курс EUR на цей місяць')),
                ('calculated_salary', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=12, verbose_name='Розрахована зарплата (грн)')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_records', to='employees.employee', verbose_name='Співробітник')),
            ],
            options={
                'verbose_name': 'Запис про зарплату',
                'verbose_name_plural': 'Записи про зарплату',
                'ordering': ['-year', '-month'],
                'unique_together': {('employee', 'month', 'year')},
            },
        ),
    ]
