# Generated by Django 5.2.4

from django.db import migrations, models

class Migration(migrations.Migration):
    initial = True
    dependencies = []
    operations = [
        migrations.CreateModel(
            name='SalaryConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('junior_base_rate', models.DecimalField(decimal_places=2, default=10000.0, max_digits=10, verbose_name='Базова ставка Junior (грн)')),
                ('middle_base_rate', models.DecimalField(decimal_places=2, default=20000.0, max_digits=10, verbose_name='Базова ставка Middle (грн)')),
                ('senior_base_rate', models.DecimalField(decimal_places=2, default=35000.0, max_digits=10, verbose_name='Базова ставка Senior (грн)')),
                ('lead_base_rate', models.DecimalField(decimal_places=2, default=50000.0, max_digits=10, verbose_name='Базова ставка Team Lead (грн)')),
                ('junior_coeff', models.DecimalField(decimal_places=2, default=1.0, max_digits=4, verbose_name='Коефіцієнт Junior')),
                ('middle_coeff', models.DecimalField(decimal_places=2, default=1.5, max_digits=4, verbose_name='Коефіцієнт Middle')),
                ('senior_coeff', models.DecimalField(decimal_places=2, default=2.0, max_digits=4, verbose_name='Коефіцієнт Senior')),
                ('lead_coeff', models.DecimalField(decimal_places=2, default=2.5, max_digits=4, verbose_name='Коефіцієнт Team Lead')),
            ],
            options={'verbose_name': 'Глобальні налаштування зарплати',},
        ),
        migrations.CreateModel(
            name='TaskType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Назва типу завдання')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Вартість (грн)')),
            ],
            options={'verbose_name': 'Тип завдання', 'verbose_name_plural': 'Типи завдань',},
        ),
    ]